version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
      - "28801:80"
      - "28802:443"
    networks:
      - some-net
    build:
      context: .
      dockerfile: Api/Dockerfile
networks:
  some-net:
    driver: bridge
