version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api:0.0.3
    ports:
      - "80:80"
      - "443:443"
    networks:
      - some-net
    build:
      context: .
      dockerfile: Api/Dockerfile
networks:
  some-net:
    driver: bridge
