version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
      - "80:28801"
      - "443:28802"
    networks:
      - some-net
    build:
      context: .
      dockerfile: Api/Dockerfile
networks:
  some-net:
    driver: bridge
